FROM golang:1.12.1

ENV GO111MODULE=off

RUN go get k8s.io/code-generator; exit 0
RUN go get k8s.io/apimachinery; exit 0
RUN go get github.com/spf13/pflag; exit 0
RUN go get k8s.io/gengo/args; exit 0

ARG repo="${GOPATH}/src/github.com/enixdark/kubernetes-programming-deepdive/Sample-controller"

RUN mkdir -p $repo

WORKDIR $GOPATH/src/k8s.io/code-generator

VOLUME $repo